# Generated by Django 4.2.4 on 2023-09-20 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_order_prepaid_postpaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='booking_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
